name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag docker push docker.pkg.github.com/matthewmanley/quotebot/QuoteBot .
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/matthewmanley/quotebot/QuoteBot
=